// api/grimorio.js
const bdGrimorio = {
    essencias: [
        { id: 'e_fogo', sub: 'Elementos Físicos', nome: 'Fogo/Calor', desc: 'Queima, aquece, ilumina, derrete.', cor: '#ff4500' },
        { id: 'e_agua', sub: 'Elementos Físicos', nome: 'Água/Líquido', desc: 'Molha, afoga, limpa, dilui.', cor: '#00bfff' },
        { id: 'e_vento', sub: 'Elementos Físicos', nome: 'Vento/Ar', desc: 'Empurra, corta, afasta gases, oxigena.', cor: '#e0ffff' },
        { id: 'e_terra', sub: 'Elementos Físicos', nome: 'Terra/Rocha', desc: 'Esmaga, cria peso, serve de base sólida.', cor: '#8b4513' },
        { id: 'e_gelo', sub: 'Elementos Físicos', nome: 'Gelo/Frio', desc: 'Congela, esfria, preserva, deixa escorregadio.', cor: '#afeeee' },
        { id: 'e_raio', sub: 'Elementos Físicos', nome: 'Raio/Eletricidade', desc: 'Dá choque, paralisa, conduz energia.', cor: '#ffd700' },
        { id: 'e_luz', sub: 'Elementos Físicos', nome: 'Luz/Brilho', desc: 'Cega inimigos, ilumina ambientes, revela.', cor: '#ffffe0' },
        { id: 'e_sombra', sub: 'Elementos Físicos', nome: 'Sombra/Escuridão', desc: 'Oculta, cega, esfria.', cor: '#4b0082' },
        { id: 'e_planta', sub: 'Elementos Físicos', nome: 'Planta/Madeira', desc: 'Amarra, cresce, serve de construção.', cor: '#228b22' },
        { id: 'e_areia', sub: 'Elementos Físicos', nome: 'Areia/Pó', desc: 'Cega, camufla, soterra, lixa.', cor: '#f4a460' },
        { id: 'e_lama', sub: 'Elementos Físicos', nome: 'Lama/Pântano', desc: 'Atola, suja, amortece quedas.', cor: '#556b2f' },
        { id: 'e_fumaca', sub: 'Elementos Físicos', nome: 'Fumaça/Gás', desc: 'Sufoca, esconde a visão, sobe pelo ar.', cor: '#696969' },
        { id: 'e_cristal', sub: 'Elementos Físicos', nome: 'Cristal/Vidro', desc: 'Perfura, reflete luz, corta, isola.', cor: '#dda0dd' },
        { id: 'e_magma', sub: 'Elementos Físicos', nome: 'Magma/Lava', desc: 'Derrete tudo, dano massivo de fogo e terra.', cor: '#ff0000' },
        { id: 'e_som', sub: 'Elementos Físicos', nome: 'Som/Vibração', desc: 'Estoura tímpanos, imita vozes, quebra vidro.', cor: '#00ced1' },
        { id: 'e_carne', sub: 'Corpo e Biologia', nome: 'Carne/Osso', desc: 'Cura ferimentos físicos, repara tecidos.', cor: '#ffb6c1' },
        { id: 'e_sangue', sub: 'Corpo e Biologia', nome: 'Sangue/Vitalidade', desc: 'Rouba vida, cicatriza, rastreia linhagem.', cor: '#8b0000' },
        { id: 'e_veneno', sub: 'Corpo e Biologia', nome: 'Veneno/Toxina', desc: 'Adoece, apodrece, corrói.', cor: '#32cd32' },
        { id: 'e_acido', sub: 'Corpo e Biologia', nome: 'Ácido/Corrosão', desc: 'Derrete metais e fechaduras.', cor: '#adff2f' },
        { id: 'e_odor', sub: 'Corpo e Biologia', nome: 'Odor/Cheiro', desc: 'Atrai monsters, esconde cheiro, enoja.', cor: '#bdb76b' },
        { id: 'e_sono', sub: 'Corpo e Biologia', nome: 'Sono/Fadiga', desc: 'Desmaia, acalma, tira a energia.', cor: '#483d8b' },
        { id: 'e_adrena', sub: 'Corpo e Biologia', nome: 'Adrenalina', desc: 'Acelera reações, tira medo, aumenta força.', cor: '#ff8c00' },
        { id: 'e_gravi', sub: 'Conceitos e Forças', nome: 'Gravidade', desc: 'Aumenta o peso ou zera o peso (flutua).', cor: '#8a2be2' },
        { id: 'e_espaco', sub: 'Conceitos e Forças', nome: 'Espaço/Vácuo', desc: 'Teletransporta, corta ignorando armadura.', cor: '#00008b' },
        { id: 'e_tempo', sub: 'Conceitos e Forças', nome: 'Tempo', desc: 'Deixa lento, rápido, rebobina segundos.', cor: '#fff8dc' },
        { id: 'e_cinet', sub: 'Conceitos e Forças', nome: 'Cinética (Impacto)', desc: 'Força de batida pura invisível.', cor: '#d3d3d3' },
        { id: 'e_magnet', sub: 'Conceitos e Forças', nome: 'Magnetismo', desc: 'Puxa ou empurra metais pesados.', cor: '#c0c0c0' },
        { id: 'e_ilusao', sub: 'Conceitos e Forças', nome: 'Ilusão/Miragem', desc: 'Cria imagens mentais falsas.', cor: '#ff69b4' },
        { id: 'e_memo', sub: 'Conceitos e Forças', nome: 'Memória', desc: 'Apaga segundos recentes ou guarda infos.', cor: '#87cefa' },
        { id: 'e_verd', sub: 'Conceitos e Forças', nome: 'Verdade', desc: 'Impede mentiras, revela o que está oculto.', cor: '#f0e68c' },
        { id: 'e_emocao', sub: 'Conceitos e Forças', nome: 'Emoção', desc: 'Causa medo, alegria, raiva ou calma.', cor: '#db7093' },
        { id: 'e_cola', sub: 'Conceitos e Forças', nome: 'Ligação (Cola)', desc: 'Gruda duas coisas com força inquebrável.', cor: '#daa520' },
        { id: 'e_atrito', sub: 'Conceitos e Forças', nome: 'Atrito', desc: 'Deixa escorregadio ou totalmente travado.', cor: '#cd853f' },
        { id: 'e_repul', sub: 'Conceitos e Forças', nome: 'Repulsão', desc: 'Como ímã invertido, afasta tudo.', cor: '#6495ed' },
        { id: 'e_absor', sub: 'Conceitos e Forças', nome: 'Absorção', desc: 'Suga impactos, água, luz ou magias.', cor: '#2f4f4f' },
        { id: 'e_elasti', sub: 'Conceitos e Forças', nome: 'Elasticidade', desc: 'Faz pedra quicar, espadas dobrarem.', cor: '#ffdab9' },
        { id: 'e_ferrug', sub: 'Conceitos e Forças', nome: 'Ferrugem/Decomp.', desc: 'Envelhece materiais rapidamente.', cor: '#a0522d' },
        { id: 'e_mudez', sub: 'Conceitos e Forças', nome: 'Mudez/Silêncio', desc: 'Apaga qualquer onda sonora da área.', cor: '#708090' },
        { id: 'e_densi', sub: 'Conceitos e Forças', nome: 'Densidade', desc: 'Faz um graveto ficar duro como aço.', cor: '#778899' },
        { id: 'e_tinta', sub: 'Conceitos e Forças', nome: 'Tinta/Registro', desc: 'Escreve, copia, marca caminhos.', cor: '#000000' }
    ],
    formas: [
        { id: 'f_flecha', sub: 'Ataque e Movimento', nome: 'Flecha/Disparo', desc: 'Um tiro reto e rápido.' },
        { id: 'f_lamina', sub: 'Ataque e Movimento', nome: 'Lâmina/Corte', desc: 'Forma um fio afiado (faca ou espada).' },
        { id: 'f_explos', sub: 'Ataque e Movimento', nome: 'Explosão/Estouro', desc: 'Expande violentamente do centro para fora.' },
        { id: 'f_corren', sub: 'Ataque e Movimento', nome: 'Corrente/Chicote', desc: 'Linha longa flexível que chicoteia/amarra.' },
        { id: 'f_cone', sub: 'Ataque e Movimento', nome: 'Cone/Sopro', desc: 'Sai de você abrindo em triângulo.' },
        { id: 'f_pilar', sub: 'Ataque e Movimento', nome: 'Pilar/Estaca', desc: 'Brota do chão ou da parede para cima.' },
        { id: 'f_chuva', sub: 'Ataque e Movimento', nome: 'Chuva/Queda', desc: 'Cai do céu atingindo uma área grande.' },
        { id: 'f_meteor', sub: 'Ataque e Movimento', nome: 'Meteoro/Massa', desc: 'Esfera gigante que cai num único ponto.' },
        { id: 'f_onda', sub: 'Ataque e Movimento', nome: 'Onda/Tsunami', desc: 'Uma parede que avança varrendo o chão.' },
        { id: 'f_bumer', sub: 'Ataque e Movimento', nome: 'Bumerangue', desc: 'Vai até um ponto e volta para você.' },
        { id: 'f_mao', sub: 'Ferramentas Físicas e Defesa', nome: 'Mão/Garra', desc: 'Agarra, aperta, pega objetos.' },
        { id: 'f_olho', sub: 'Ferramentas Físicas e Defesa', nome: 'Olho/Lente', desc: 'Permite enxergar, aumenta a visão (lupa).' },
        { id: 'f_ouvid', sub: 'Ferramentas Físicas e Defesa', nome: 'Ouvido/Funil', desc: 'Capta sons distantes.' },
        { id: 'f_parede', sub: 'Ferramentas Físicas e Defesa', nome: 'Parede/Escudo', desc: 'Uma barreira plana e imóvel.' },
        { id: 'f_cupula', sub: 'Ferramentas Físicas e Defesa', nome: 'Cúpula/Redoma', desc: 'Meia-esfera protetora sobre uma área.' },
        { id: 'f_esfera', sub: 'Ferramentas Físicas e Defesa', nome: 'Esfera/Bolha', desc: 'Uma bola perfeita (pode ser oca).' },
        { id: 'f_fio', sub: 'Ferramentas Físicas e Defesa', nome: 'Fio/Corda', desc: 'Linha longa para pendurar ou tecer.' },
        { id: 'f_roda', sub: 'Ferramentas Físicas e Defesa', nome: 'Roda/Engrenagem', desc: 'Algo circular que gira.' },
        { id: 'f_asa', sub: 'Ferramentas Físicas e Defesa', nome: 'Asa/Pena', desc: 'Permite planar, voar ou criar vento.' },
        { id: 'f_degrau', sub: 'Ferramentas Físicas e Defesa', nome: 'Degrau/Plataforma', desc: 'Uma base plana no ar para pisar.' },
        { id: 'f_ponte', sub: 'Ferramentas Físicas e Defesa', nome: 'Ponte/Caminho', desc: 'Uma passarela longa.' },
        { id: 'f_porta', sub: 'Ferramentas Físicas e Defesa', nome: 'Porta/Fresta', desc: 'Cria uma passagem onde não tem.' },
        { id: 'f_chave', sub: 'Ferramentas Físicas e Defesa', nome: 'Chave/Pino', desc: 'Entra em buracos com a forma exata.' },
        { id: 'f_rede', sub: 'Ferramentas Físicas e Defesa', nome: 'Rede/Teia', desc: 'Malha cruzada para capturar/amortecer.' },
        { id: 'f_tapete', sub: 'Ferramentas Físicas e Defesa', nome: 'Tapete/Piso', desc: 'Fica rente ao chão.' },
        { id: 'f_espelh', sub: 'Formas Complexas e Autônomas', nome: 'Espelho/Refletor', desc: 'Devolve o que bater nele.' },
        { id: 'f_buraco', sub: 'Formas Complexas e Autônomas', nome: 'Buraco/Cratera', desc: 'Abre uma cavidade para baixo.' },
        { id: 'f_armadi', sub: 'Formas Complexas e Autônomas', nome: 'Armadilha/Mina', desc: 'Escondido esperando algo pisar.' },
        { id: 'f_aura', sub: 'Formas Complexas e Autônomas', nome: 'Aura/Veste', desc: 'Cobre o seu corpo como uma roupa.' },
        { id: 'f_nuvem', sub: 'Formas Complexas e Autônomas', nome: 'Nuvem/Névoa', desc: 'Se espalha pelo ar preenchendo o ambiente.' },
        { id: 'f_vortic', sub: 'Formas Complexas e Autônomas', nome: 'Vórtice/Redemoinho', desc: 'Gira sugando tudo para o centro.' },
        { id: 'f_servo', sub: 'Formas Complexas e Autônomas', nome: 'Servo/Boneco', desc: 'Um avatar bípede para tarefas burras.' },
        { id: 'f_passar', sub: 'Formas Complexas e Autônomas', nome: 'Pássaro/Mensag.', desc: 'Forma voadora autônoma para longas dist.' },
        { id: 'f_carapa', sub: 'Formas Complexas e Autônomas', nome: 'Carapaça', desc: 'Envolve corpo aliado como armadura grossa.' },
        { id: 'f_agulha', sub: 'Formas Complexas e Autônomas', nome: 'Agulha/Seringa', desc: 'Fina o suficiente para pele ou fechaduras.' },
        { id: 'f_tubo', sub: 'Formas Complexas e Autônomas', nome: 'Tubo/Cano', desc: 'Canal oco por onde coisas podem passar.' },
        { id: 'f_gancho', sub: 'Formas Complexas e Autônomas', nome: 'Gancho/Anzol', desc: 'Puxa e trava em quinas.' },
        { id: 'f_guarda', sub: 'Formas Complexas e Autônomas', nome: 'Guarda-chuva', desc: 'Protege apenas de coisas caindo de cima.' },
        { id: 'f_mola', sub: 'Formas Complexas e Autônomas', nome: 'Mola', desc: 'Comprime e ejeta com força.' },
        { id: 'f_coroa', sub: 'Formas Complexas e Autônomas', nome: 'Coroa/Anel', desc: 'Circula a cabeça (bom para magia mental).' }
    ],
    modificadores: [
        { id: 'm_tempor', sub: 'Tempo e Gatilho', nome: 'Temporizador', desc: 'Desliga sozinho depois de X horas/minutos.' },
        { id: 'm_atraso', sub: 'Tempo e Gatilho', nome: 'Atraso/Timer', desc: 'Só ativa X tempo depois de desenhar.' },
        { id: 'm_condic', sub: 'Tempo e Gatilho', nome: 'Condicional', desc: 'Só funciona se a condição acontecer.' },
        { id: 'm_perman', sub: 'Tempo e Gatilho', nome: 'Permanente', desc: 'Nunca desliga (gasta muita mana).' },
        { id: 'm_eco', sub: 'Tempo e Gatilho', nome: 'Eco/Repetição', desc: 'Acontece duas vezes seguidas.' },
        { id: 'm_gigant', sub: 'Espaço e Tamanho', nome: 'Gigante', desc: 'Multiplica o tamanho da forma.' },
        { id: 'm_minusc', sub: 'Espaço e Tamanho', nome: 'Minúsculo', desc: 'Encolhe para o tamanho de uma moeda.' },
        { id: 'm_telegu', sub: 'Espaço e Tamanho', nome: 'Teleguiado', desc: 'Faz curva no ar perseguindo um alvo.' },
        { id: 'm_perfur', sub: 'Espaço e Tamanho', nome: 'Perfurante', desc: 'Atravessa a primeira coisa que bater.' },
        { id: 'm_adesiv', sub: 'Espaço e Tamanho', nome: 'Adesivo/Grudento', desc: 'Magia não se mexe, fica colada no local.' },
        { id: 'm_invisi', sub: 'Furtividade e Utilidade', nome: 'Invisível', desc: 'A forma gerada não pode ser vista.' },
        { id: 'm_silenc', sub: 'Furtividade e Utilidade', nome: 'Silencioso', desc: 'Anula seu próprio som ao existir.' },
        { id: 'm_falso', sub: 'Furtividade e Utilidade', nome: 'Falso/Camuflado', desc: 'Tem a aparência de um item comum.' },
        { id: 'm_limpo', sub: 'Furtividade e Utilidade', nome: 'Limpo', desc: 'Não deixa rastros mágicos ou físicos.' },
        { id: 'm_partil', sub: 'Furtividade e Utilidade', nome: 'Partilhado', desc: 'Efeito se aplica a quem você der a mão.' },
        { id: 'm_vampir', sub: 'Efeitos Especiais', nome: 'Vampírico', desc: 'O que tirar do alvo, passa pra você.' },
        { id: 'm_protet', sub: 'Efeitos Especiais', nome: 'Protetor/Amigo', desc: 'Reconhece aliados e não dá dano neles.' },
        { id: 'm_revers', sub: 'Efeitos Especiais', nome: 'Reversível', desc: 'Pode cancelar de longe num estalo.' },
        { id: 'm_adapta', sub: 'Efeitos Especiais', nome: 'Adaptável', desc: 'Elemento muda sozinho pela necessidade.' },
        { id: 'm_ligaca', sub: 'Efeitos Especiais', nome: 'Ligação Mental', desc: 'Enxerga/sente através da magia.' }
    ],
    gatilhos: [
        { id: 'g_impact', sub: 'Físicos e Mecânicos', nome: 'Impacto/Pancada', desc: 'Ativa quando o objeto bate forte em algo (pontas de flecha).' },
        { id: 'g_fricca', sub: 'Físicos e Mecânicos', nome: 'Fricção', desc: 'Ativa ao esfregar o objeto (riscar ou girar anel).' },
        { id: 'g_quebra', sub: 'Físicos e Mecânicos', nome: 'Quebra/Rompimento', desc: 'A magia fica guardada e explode se o objeto for destruído.' },
        { id: 'g_tensao', sub: 'Físicos e Mecânicos', nome: 'Tensão', desc: 'Liga quando algo é esticado (ex: corda do arco).' },
        { id: 'g_abertu', sub: 'Físicos e Mecânicos', nome: 'Abertura', desc: 'Desperta quando porta, livro ou baú é aberto.' },
        { id: 'g_fecham', sub: 'Físicos e Mecânicos', nome: 'Fechamento', desc: 'O inverso; liga assim que a tampa se fecha.' },
        { id: 'g_rotaca', sub: 'Físicos e Mecânicos', nome: 'Rotação', desc: 'Ativa ao girar o objeto (maçaneta ou tampa).' },
        { id: 'g_queliv', sub: 'Físicos e Mecânicos', nome: 'Queda Livre', desc: 'Sensor liga assim que perde contato com o chão/mão.' },
        { id: 'g_imersa', sub: 'Físicos e Mecânicos', nome: 'Imersão', desc: 'Só funciona quando afunda totalmente na água.' },
        { id: 'g_perfur', sub: 'Físicos e Mecânicos', nome: 'Perfuração', desc: 'Ativa no exato momento em que fura a pele/armadura.' },
        { id: 'g_senha',  sub: 'Interação Pessoal (Biometria)', nome: 'Senha Falada', desc: 'Só ativa se ouvir uma palavra específica.' },
        { id: 'g_sopro',  sub: 'Interação Pessoal (Biometria)', nome: 'Sopro/Vento', desc: 'Liga quando você sopra diretamente sobre a runa.' },
        { id: 'g_toque',  sub: 'Interação Pessoal (Biometria)', nome: 'Toque de Pele', desc: 'Precisa de contato direto com pele nua.' },
        { id: 'g_inmana', sub: 'Interação Pessoal (Biometria)', nome: 'Injeção de Mana', desc: 'Exige um "choquinho" da sua energia para ligar.' },
        { id: 'g_assina', sub: 'Interação Pessoal (Biometria)', nome: 'Assinatura', desc: 'Impressão digital; recusa funcionar para outros.' },
        { id: 'g_aperto', sub: 'Interação Pessoal (Biometria)', nome: 'Aperto Firme', desc: 'Ativa se esmagado ou segurado com muita força.' },
        { id: 'g_focvis', sub: 'Interação Pessoal (Biometria)', nome: 'Foco Visual', desc: 'Desenhado em óculos; ativa ao piscar/focar.' },
        { id: 'g_gotasn', sub: 'Interação Pessoal (Biometria)', nome: 'Gota de Sangue', desc: 'Exige sacrifício; o selo liga ao furar o dedo.' },
        { id: 'g_ritmoc', sub: 'Interação Pessoal (Biometria)', nome: 'Ritmo Cardíaco', desc: 'Lê o pulso. Pode ativar no susto (pulso rápido).' },
        { id: 'g_assobi', sub: 'Interação Pessoal (Biometria)', nome: 'Assobio/Estalo', desc: 'Ativa com um som agudo específico gerado por você.' },
        { id: 'g_proxim', sub: 'Sensores Ambientais', nome: 'Proximidade', desc: 'Radar invisível. Ativa a menos de 3 metros.' },
        { id: 'g_luzsol', sub: 'Sensores Ambientais', nome: 'Luz Solar', desc: 'A magia "acorda" assim que o sol bate direto.' },
        { id: 'g_escuri', sub: 'Sensores Ambientais', nome: 'Escuridão Total', desc: 'Só funciona quando não há fonte de luz perto.' },
        { id: 'g_mudtem', sub: 'Sensores Ambientais', nome: 'Mudança de Temp.', desc: 'Ativa se o local ficar subitamente muito quente/frio.' },
        { id: 'g_sensfm', sub: 'Sensores Ambientais', nome: 'Sensor de Fumaça', desc: 'Liga automaticamente se detectar toxinas no ar.' },
        { id: 'g_conmet', sub: 'Sensores Ambientais', nome: 'Contato Metálico', desc: 'A runa desperta se encostar em ferro ou aço.' },
        { id: 'g_alilun', sub: 'Sensores Ambientais', nome: 'Alinhamento Lunar', desc: 'Só funciona à noite ou em uma fase da lua.' },
        { id: 'g_altitu', sub: 'Sensores Ambientais', nome: 'Altitude', desc: 'Só ativa se estiver a mais de 10 metros de altura.' },
        { id: 'g_barulh', sub: 'Sensores Ambientais', nome: 'Barulho Extremo', desc: 'Ativa sozinho se alguém gritar ou houver explosão.' },
        { id: 'g_pressn', sub: 'Sensores Ambientais', nome: 'Presença Sangue', desc: 'Desperta se "farejar" sangue fresco no ar.' },
        { id: 'g_saquep', sub: 'Combate e Reações Táticas', nome: 'Saque Rápido', desc: 'A arma liga seus poderes ao ser puxada da bainha.' },
        { id: 'g_acertc', sub: 'Combate e Reações Táticas', nome: 'Acerto Crítico', desc: 'O efeito extra só acontece se o golpe for letal.' },
        { id: 'g_defper', sub: 'Combate e Reações Táticas', nome: 'Defesa Perfeita', desc: 'Runa gasta magia só ao bloquear com sucesso.' },
        { id: 'g_dordan', sub: 'Combate e Reações Táticas', nome: 'Dor/Dano', desc: 'O objeto liga sozinho no momento em que você toma dano.' },
        { id: 'g_hommor', sub: 'Combate e Reações Táticas', nome: 'Homem-Morto', desc: 'Gatilho perigoso; só ativa se você cair inconsciente.' },
        { id: 'g_desarm', sub: 'Combate e Reações Táticas', nome: 'Desarme', desc: 'Segurança; item dá choque se arrancado da sua mão.' },
        { id: 'g_miratr', sub: 'Combate e Reações Táticas', nome: 'Mira Travada', desc: 'Ativa após apontar a arma para o alvo por 3 seg.' },
        { id: 'g_deflex', sub: 'Combate e Reações Táticas', nome: 'Deflexão', desc: 'Poder desperta ao rebater projétil inimigo.' },
        { id: 'g_blomov', sub: 'Combate e Reações Táticas', nome: 'Bloqueio de Mov.', desc: 'Ativa se você for paralisado, congelado ou amarrado.' },
        { id: 'g_ultrec', sub: 'Combate e Reações Táticas', nome: 'Último Recurso', desc: 'O item só libera a magia se você tiver -10% de vida.' },
        { id: 'g_atraso', sub: 'Tempo e Regras Especiais', nome: 'Atraso (Timer)', desc: 'Magia não sai na hora. Você define o delay.' },
        { id: 'g_tmpdia', sub: 'Tempo e Regras Especiais', nome: 'Temporizador Diário', desc: 'Relógio mágico. Ativa sozinho todo dia ao meio-dia.' },
        { id: 'g_ecomag', sub: 'Tempo e Regras Especiais', nome: 'Eco Mágico', desc: 'Desperta se alguém conjurar magia perto de você.' },
        { id: 'g_absfei', sub: 'Tempo e Regras Especiais', nome: 'Absorção de Feitiço', desc: 'Engole magia recebida e altera seu próprio efeito.' },
        { id: 'g_comtel', sub: 'Tempo e Regras Especiais', nome: 'Comando Mental', desc: 'Pode ativar o objeto a distância só de pensar.' },
        { id: 'g_espelh', sub: 'Tempo e Regras Especiais', nome: 'Espelhamento', desc: 'Só ataca se o inimigo atacar primeiro (legítima defesa).' },
        { id: 'g_limcar', sub: 'Tempo e Regras Especiais', nome: 'Limite de Cargas', desc: 'Ativa até 3 vezes perfeitamente. Depois, apaga.' },
        { id: 'g_conesp', sub: 'Tempo e Regras Especiais', nome: 'Condição de Espécie', desc: 'Exige alvo específico (ex: flecha para morto-vivo).' },
        { id: 'g_detmen', sub: 'Tempo e Regras Especiais', nome: 'Detecção de Mentira', desc: 'Liga/esquenta se a pessoa que segura mentir.' },
        { id: 'g_roletr', sub: 'Tempo e Regras Especiais', nome: 'Roleta Russa', desc: 'Gatilho corrompido: 50% de chance de falhar.' }
    ]
};

// Esta função trata os pedidos e responde com o Grimório de forma segura
export default function handler(req, res) {
    // Permite apenas pedidos GET (leitura do grimório)
    if (req.method === 'GET') {
        return res.status(200).json(bdGrimorio);
    }
    
    return res.status(405).json({ message: 'Método não permitido.' });
}